name: Push Docker Image to ECR
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch; adjust as needed
jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <REGION>
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region <REGION> | \
          docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com
      - name: Build Docker image
        run: |
          docker build -t <REPOSITORY_NAME>:<IMAGE_TAG> .
      - name: Tag Docker image
        run: |
          docker tag <REPOSITORY_NAME>:<IMAGE_TAG> <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<REPOSITORY_NAME>:<IMAGE_TAG>
      - name: Push Docker image to ECR
        run: |
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<REPOSITORY_NAME>:<IMAGE_TAG>